# Form implementation generated from reading ui file 'Alarmclock_Timer.ui'
#
# Created by: PyQt6 UI code generator 6.3.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class UiMainWindow(object):
    def setup_ui(self, main_window):
        main_window.setObjectName("main_window")
        main_window.setWindowModality(QtCore.Qt.WindowModality.NonModal)
        main_window.setEnabled(True)
        main_window.resize(600, 500)
        main_window.setMinimumSize(QtCore.QSize(600, 500))
        main_window.setMaximumSize(QtCore.QSize(600, 500))
        main_window.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.ArrowCursor))
        main_window.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.DefaultContextMenu)
        main_window.setStyleSheet("background-color: #0d1131;")
        main_window.setIconSize(QtCore.QSize(24, 24))
        main_window.setToolButtonStyle(QtCore.Qt.ToolButtonStyle.ToolButtonIconOnly)
        main_window.setAnimated(False)
        main_window.setTabShape(QtWidgets.QTabWidget.TabShape.Rounded)
        self.centralwidget = QtWidgets.QWidget(main_window)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(10, 10, 580, 480))
        self.frame.setStyleSheet("background-color: #181b3f;\n"
                                 "border-radius: 20")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setGeometry(QtCore.QRect(0, 0, 580, 130))
        self.frame_2.setStyleSheet("background-color: #282e5c;\n"
                                   "border-radius: 20")
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label_3 = QtWidgets.QLabel(self.frame_2)
        self.label_3.setGeometry(QtCore.QRect(100, 35, 461, 60))
        font = QtGui.QFont()
        font.setFamily("Unispace")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: white;\n"
                                   "")
        self.label_3.setTextFormat(QtCore.Qt.TextFormat.AutoText)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.frame_2)
        self.label_4.setGeometry(QtCore.QRect(20, 15, 70, 100))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("../../Desktop/Python/timer/sendtimepick1.png"))
        self.label_4.setObjectName("label_4")
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setGeometry(QtCore.QRect(10, 140, 275, 330))
        self.frame_3.setAcceptDrops(False)
        self.frame_3.setStyleSheet("background-color: #282e5c;\n"
                                   "border-radius: 20")
        self.frame_3.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_3.setObjectName("frame_3")
        self.label = QtWidgets.QLabel(self.frame_3)
        self.label.setGeometry(QtCore.QRect(37, 30, 200, 185))
        self.label.setAcceptDrops(False)
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("../../Desktop/Python/timer/alarmclock_icon1___копия-removebg-preview.png"))
        self.label.setObjectName("label")
        self.alarm_btn = QtWidgets.QPushButton(self.frame_3)
        self.alarm_btn.setGeometry(QtCore.QRect(42, 250, 190, 45))
        font = QtGui.QFont()
        font.setFamily("Unispace")
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        font.setKerning(True)
        self.alarm_btn.setFont(font)
        self.alarm_btn.setStyleSheet("QPushButton {    \n"
                                     "    border: 3px solid #3051a8;\n"
                                     "    border-radius: 20;\n"
                                     "    color: white;\n"
                                     "}\n"
                                     "\n"
                                     "QPushButton:hover {\n"
                                     "    background-color: #3051a8\n"
                                     "}\n"
                                     "\n"
                                     "QPushButton:pressed {\n"
                                     "    background-color: #3bf3d4\n"
                                     "}")
        self.alarm_btn.setObjectName("alarm_btn")
        self.frame_4 = QtWidgets.QFrame(self.frame)
        self.frame_4.setGeometry(QtCore.QRect(295, 140, 275, 330))
        self.frame_4.setAcceptDrops(False)
        self.frame_4.setStyleSheet("background-color: #282e5c;\n"
                                   "border-radius: 20")
        self.frame_4.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_4.setObjectName("frame_4")
        self.timer_btn = QtWidgets.QPushButton(self.frame_4)
        self.timer_btn.setGeometry(QtCore.QRect(42, 250, 190, 45))
        font = QtGui.QFont()
        font.setFamily("Unispace")
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.timer_btn.setFont(font)
        self.timer_btn.setMouseTracking(False)
        self.timer_btn.setTabletTracking(False)
        self.timer_btn.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.DefaultContextMenu)
        self.timer_btn.setAcceptDrops(False)
        self.timer_btn.setStyleSheet("QPushButton {    \n"
                                     "    border: 3px solid #3051a8;\n"
                                     "    border-radius: 20;\n"
                                     "    color: white;\n"
                                     "}\n"
                                     "\n"
                                     "QPushButton:hover {\n"
                                     "    background-color: #3051a8\n"
                                     "}\n"
                                     "\n"
                                     "QPushButton:pressed {\n"
                                     "    background-color: #3bf3d4\n"
                                     "}")
        self.timer_btn.setDefault(False)
        self.timer_btn.setFlat(False)
        self.timer_btn.setObjectName("timer_btn")
        self.label_2 = QtWidgets.QLabel(self.frame_4)
        self.label_2.setGeometry(QtCore.QRect(37, 25, 200, 185))
        self.label_2.setAcceptDrops(False)
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("../../Desktop/Python/timer/timer_icon_1.2 — копия.png"))
        self.label_2.setObjectName("label_2")
        main_window.setCentralWidget(self.centralwidget)

        self.retranslate_ui(main_window)
        QtCore.QMetaObject.connectSlotsByName(main_window)

    def retranslate_ui(self, main_window):
        _translate = QtCore.QCoreApplication.translate
        main_window.setWindowTitle(_translate("main_window", "main_window"))
        self.label_3.setText(_translate("main_window", "Select application type"))
        self.alarm_btn.setText(_translate("main_window", "Alarm Clock"))
        self.timer_btn.setText(_translate("main_window", "Timer"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    main_window = QtWidgets.QMainWindow()
    ui = UiMainWindow()
    ui.setupUi(main_window)
    main_window.show()
    sys.exit(app.exec())
