# Form implementation generated from reading ui file 'Timer_Update.ui'
#
# Created by: PyQt6 UI code generator 6.3.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class UiTimer(object):
    def setup_ui(self, timer):
        timer.setObjectName("timer")
        timer.resize(600, 500)
        timer.setMinimumSize(QtCore.QSize(600, 500))
        timer.setMaximumSize(QtCore.QSize(600, 500))
        timer.setAutoFillBackground(False)
        timer.setStyleSheet("background-color: #0d1131;")
        self.centralwidget = QtWidgets.QWidget(timer)
        self.centralwidget.setObjectName("centralwidget")
        self.frame_main = QtWidgets.QFrame(self.centralwidget)
        self.frame_main.setGeometry(QtCore.QRect(10, 10, 580, 480))
        self.frame_main.setStyleSheet("background-color: #181b3f;\n"
                                      "border-radius: 20")
        self.frame_main.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_main.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_main.setObjectName("frame_main")
        self.frame_up = QtWidgets.QFrame(self.frame_main)
        self.frame_up.setGeometry(QtCore.QRect(0, 0, 580, 130))
        self.frame_up.setStyleSheet("background-color: #282e5c;\n"
                                    "border-radius: 20")
        self.frame_up.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_up.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_up.setObjectName("frame_up")
        self.label = QtWidgets.QLabel(self.frame_up)
        self.label.setGeometry(QtCore.QRect(120, 45, 101, 41))
        font = QtGui.QFont()
        font.setFamily("Unispace")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color: white")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.frame_up)
        self.label_2.setGeometry(QtCore.QRect(20, 20, 101, 81))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("../../Desktop/Python/timer/timer_int_2.png"))
        self.label_2.setObjectName("label_2")
        self.back_btn = QtWidgets.QPushButton(self.frame_up)
        self.back_btn.setGeometry(QtCore.QRect(480, 45, 80, 40))
        font = QtGui.QFont()
        font.setFamily("Unispace")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.back_btn.setFont(font)
        self.back_btn.setStyleSheet("QPushButton {    \n"
                                    "    border: 3px solid #a81111;\n"
                                    "    background-color: #700404;\n"
                                    "    border-radius: 20;\n"
                                    "    color: white;\n"
                                    "}\n"
                                    "\n"
                                    "QPushButton:hover {\n"
                                    "    background-color: #a81111\n"
                                    "}\n"
                                    "\n"
                                    "QPushButton:pressed {\n"
                                    "    background-color: #610202;\n"
                                    "    border: 3px solid #610202;\n"
                                    "}")
        self.back_btn.setObjectName("back_btn")
        self.label_3 = QtWidgets.QLabel(self.frame_up)
        self.label_3.setGeometry(QtCore.QRect(280, 10, 150, 40))
        font = QtGui.QFont()
        font.setFamily("Unispace")
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: #ff5398")
        self.label_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.time_label = QtWidgets.QLabel(self.frame_up)
        self.time_label.setGeometry(QtCore.QRect(270, 60, 175, 50))
        font = QtGui.QFont()
        font.setFamily("Unispace")
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.time_label.setFont(font)
        self.time_label.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.time_label.setStyleSheet("color: #3870ec;\n"
                                      "background-color: #1a1f4a")
        self.time_label.setTextFormat(QtCore.Qt.TextFormat.PlainText)
        self.time_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.time_label.setObjectName("time_label")
        self.frame_down = QtWidgets.QFrame(self.frame_main)
        self.frame_down.setGeometry(QtCore.QRect(10, 140, 560, 331))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.frame_down.setFont(font)
        self.frame_down.setStyleSheet("background-color: #282e5c;\n"
                                      "border-radius: 20")
        self.frame_down.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_down.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_down.setObjectName("frame_down")
        self.label_4 = QtWidgets.QLabel(self.frame_down)
        self.label_4.setGeometry(QtCore.QRect(30, 10, 401, 51))
        font = QtGui.QFont()
        font.setFamily("Unispace")
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: #ff5398")
        self.label_4.setObjectName("label_4")
        self.sec_sb = QtWidgets.QSpinBox(self.frame_down)
        self.sec_sb.setGeometry(QtCore.QRect(465, 65, 50, 120))
        font = QtGui.QFont()
        font.setFamily("Unispace")
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.sec_sb.setFont(font)
        self.sec_sb.setStatusTip("")
        self.sec_sb.setWhatsThis("")
        self.sec_sb.setAccessibleName("")
        self.sec_sb.setAccessibleDescription("")
        self.sec_sb.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.sec_sb.setStyleSheet("QSpinBox\n"
                                  "{\n"
                                  "    selection-background-color: #282e5c;\n"
                                  "    color: white;\n"
                                  "    padding-right: 5px;\n"
                                  "    padding-left: 5px;\n"
                                  "    padding-top: 25px;\n"
                                  "    padding-bottom: 25px;\n"
                                  "}\n"
                                  "\n"
                                  "QSpinBox::up-button\n"
                                  "{\n"
                                  "    width:45px;\n"
                                  "    height: 30px;\n"
                                  "    right: 3px;\n"
                                  "    top: 2px;\n"
                                  "}\n"
                                  "\n"
                                  "QSpinBox::down-button\n"
                                  "{\n"
                                  "    width:45px;\n"
                                  "    height: 30px;\n"
                                  "    right: 3px;\n"
                                  "    bottom: 2 px;\n"
                                  "}")
        self.sec_sb.setInputMethodHints(QtCore.Qt.InputMethodHint.ImhDigitsOnly)
        self.sec_sb.setWrapping(False)
        self.sec_sb.setFrame(True)
        self.sec_sb.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.sec_sb.setReadOnly(False)
        self.sec_sb.setButtonSymbols(QtWidgets.QAbstractSpinBox.ButtonSymbols.UpDownArrows)
        self.sec_sb.setSpecialValueText("")
        self.sec_sb.setKeyboardTracking(True)
        self.sec_sb.setMaximum(59)
        self.sec_sb.setObjectName("sec_sb")
        self.run_btn = QtWidgets.QPushButton(self.frame_down)
        self.run_btn.setGeometry(QtCore.QRect(180, 210, 200, 45))
        font = QtGui.QFont()
        font.setFamily("Unispace")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.run_btn.setFont(font)
        self.run_btn.setStyleSheet("QPushButton {    \n"
                                   "    border: 3px solid #3051a8;\n"
                                   "    border-radius: 20;\n"
                                   "    color: white;\n"
                                   "}\n"
                                   "\n"
                                   "QPushButton:hover {\n"
                                   "    background-color: #3051a8\n"
                                   "}\n"
                                   "\n"
                                   "QPushButton:pressed {\n"
                                   "    background-color: #3bf3d4\n"
                                   "}")
        self.run_btn.setObjectName("run_btn")
        self.label_5 = QtWidgets.QLabel(self.frame_down)
        self.label_5.setGeometry(QtCore.QRect(45, 110, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Unispace")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color: #4f5991\n"
                                   "")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.frame_down)
        self.label_6.setGeometry(QtCore.QRect(215, 110, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Unispace")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color: #4f5991\n"
                                   "")
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.frame_down)
        self.label_7.setGeometry(QtCore.QRect(385, 110, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Unispace")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("color: #4f5991\n"
                                   "")
        self.label_7.setObjectName("label_7")
        self.hour_sb = QtWidgets.QSpinBox(self.frame_down)
        self.hour_sb.setGeometry(QtCore.QRect(125, 65, 50, 120))
        font = QtGui.QFont()
        font.setFamily("Unispace")
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.hour_sb.setFont(font)
        self.hour_sb.setToolTip("")
        self.hour_sb.setStatusTip("")
        self.hour_sb.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.hour_sb.setAutoFillBackground(False)
        self.hour_sb.setStyleSheet("QSpinBox\n"
                                   "{\n"
                                   "    selection-background-color: #282e5c;\n"
                                   "    color: white;\n"
                                   "    padding-right: 5px;\n"
                                   "    padding-left: 5px;\n"
                                   "    padding-top: 25px;\n"
                                   "    padding-bottom: 25px;\n"
                                   "}\n"
                                   "\n"
                                   "QSpinBox::up-button\n"
                                   "{\n"
                                   "    width:45px;\n"
                                   "    height: 30px;\n"
                                   "    right: 3px;\n"
                                   "    top: 2px;\n"
                                   "}\n"
                                   "\n"
                                   "QSpinBox::up-arrow \n"
                                   "{\n"
                                   "    \n"
                                   "}\n"
                                   "\n"
                                   "QSpinBox::down-button\n"
                                   "{\n"
                                   "    width:45px;\n"
                                   "    height: 30px;\n"
                                   "    right: 3px;\n"
                                   "    bottom: 2 px;\n"
                                   "}")
        self.hour_sb.setWrapping(False)
        self.hour_sb.setFrame(True)
        self.hour_sb.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.hour_sb.setButtonSymbols(QtWidgets.QAbstractSpinBox.ButtonSymbols.UpDownArrows)
        self.hour_sb.setSpecialValueText("")
        self.hour_sb.setKeyboardTracking(True)
        self.hour_sb.setMaximum(24)
        self.hour_sb.setObjectName("hour_sb")
        self.min_sb = QtWidgets.QSpinBox(self.frame_down)
        self.min_sb.setGeometry(QtCore.QRect(295, 65, 50, 120))
        font = QtGui.QFont()
        font.setFamily("Unispace")
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.min_sb.setFont(font)
        self.min_sb.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.min_sb.setStyleSheet("QSpinBox\n"
                                  "{\n"
                                  "    selection-background-color: #282e5c;\n"
                                  "    color: white;\n"
                                  "    padding-right: 5px;\n"
                                  "    padding-left: 5px;\n"
                                  "    padding-top: 25px;\n"
                                  "    padding-bottom: 25px;\n"
                                  "}\n"
                                  "\n"
                                  "QSpinBox::up-button\n"
                                  "{\n"
                                  "    width:45px;\n"
                                  "    height: 30px;\n"
                                  "    right: 3px;\n"
                                  "    top: 2px;\n"
                                  "}\n"
                                  "\n"
                                  "QSpinBox::down-button\n"
                                  "{\n"
                                  "    width:45px;\n"
                                  "    height: 30px;\n"
                                  "    right: 3px;\n"
                                  "    bottom: 2 px;\n"
                                  "}")
        self.min_sb.setWrapping(False)
        self.min_sb.setFrame(True)
        self.min_sb.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.min_sb.setButtonSymbols(QtWidgets.QAbstractSpinBox.ButtonSymbols.UpDownArrows)
        self.min_sb.setSpecialValueText("")
        self.min_sb.setKeyboardTracking(True)
        self.min_sb.setMaximum(59)
        self.min_sb.setObjectName("min_sb")
        self.stop_btn = QtWidgets.QPushButton(self.frame_down)
        self.stop_btn.setEnabled(True)
        self.stop_btn.setGeometry(QtCore.QRect(400, 270, 100, 45))
        font = QtGui.QFont()
        font.setFamily("Unispace")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.stop_btn.setFont(font)
        self.stop_btn.setStyleSheet("QPushButton {    \n"
                                    "    border: 3px solid #a81111;\n"
                                    "    background-color: #700404;\n"
                                    "    border-radius: 20;\n"
                                    "    color: white;\n"
                                    "}\n"
                                    "\n"
                                    "QPushButton:hover {\n"
                                    "    background-color: #a81111\n"
                                    "}\n"
                                    "\n"
                                    "QPushButton:pressed {\n"
                                    "    background-color: #610202;\n"
                                    "    border: 3px solid #610202;\n"
                                    "}")
        self.stop_btn.setDefault(False)
        self.stop_btn.setObjectName("stop_btn")
        self.countdown_lab = QtWidgets.QLabel(self.frame_down)
        self.countdown_lab.setGeometry(QtCore.QRect(200, 270, 181, 50))
        font = QtGui.QFont()
        font.setFamily("Unispace")
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.countdown_lab.setFont(font)
        self.countdown_lab.setStyleSheet("color: white")
        self.countdown_lab.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.countdown_lab.setObjectName("countdown_lab")
        self.time_left_lab = QtWidgets.QLabel(self.frame_down)
        self.time_left_lab.setEnabled(False)
        self.time_left_lab.setGeometry(QtCore.QRect(30, 275, 171, 40))
        font = QtGui.QFont()
        font.setFamily("Unispace")
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.time_left_lab.setFont(font)
        self.time_left_lab.setStyleSheet("color: #ff5398")
        self.time_left_lab.setObjectName("time_left_lab")
        timer.setCentralWidget(self.centralwidget)

        self.retranslate_ui(timer)
        QtCore.QMetaObject.connectSlotsByName(timer)

    def retranslate_ui(self, timer):
        _translate = QtCore.QCoreApplication.translate
        timer.setWindowTitle(_translate("timer", "MainWindow"))
        self.label.setText(_translate("timer", "Timer"))
        self.back_btn.setText(_translate("timer", "Back"))
        self.label_3.setText(_translate("timer", "Time now"))
        self.time_label.setText(_translate("timer", "23:59:59"))
        self.label_4.setText(_translate("timer", "Set the time for timer"))
        self.run_btn.setText(_translate("timer", "Run Timer"))
        self.label_5.setText(_translate("timer", "Hours"))
        self.label_6.setText(_translate("timer", "Min-s"))
        self.label_7.setText(_translate("timer", "Sec-s"))
        self.stop_btn.setText(_translate("timer", "Stop"))
        self.countdown_lab.setText(_translate("timer", "23:59:59"))
        self.time_left_lab.setText(_translate("timer", "Time left"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    timer = QtWidgets.QMainWindow()
    ui = UiTimer()
    ui._u(timer)
    timer.show()
    sys.exit(app.exec())
