# Form implementation generated from reading ui file 'timer.ui'
#
# Created by: PyQt6 UI code generator 6.3.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_AlarmClock(object):
    def setupUi(self, AlarmClock):
        AlarmClock.setObjectName("AlarmClock")
        AlarmClock.resize(600, 500)
        AlarmClock.setMinimumSize(QtCore.QSize(600, 500))
        AlarmClock.setMaximumSize(QtCore.QSize(600, 500))
        AlarmClock.setAutoFillBackground(False)
        AlarmClock.setStyleSheet("background-color: #0d1131;")
        self.centralwidget = QtWidgets.QWidget(AlarmClock)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(10, 10, 580, 480))
        self.frame.setStyleSheet("background-color: #181b3f;\n"
"border-radius: 20")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setGeometry(QtCore.QRect(0, 0, 580, 130))
        self.frame_2.setStyleSheet("background-color: #282e5c;\n"
"border-radius: 20")
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label = QtWidgets.QLabel(self.frame_2)
        self.label.setGeometry(QtCore.QRect(120, 45, 101, 41))
        font = QtGui.QFont()
        font.setFamily("Unispace")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color: white")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.frame_2)
        self.label_2.setGeometry(QtCore.QRect(20, 20, 101, 81))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("../../Desktop/Python/timer/timer_int_2.png"))
        self.label_2.setObjectName("label_2")
        self.pushButton = QtWidgets.QPushButton(self.frame_2)
        self.pushButton.setGeometry(QtCore.QRect(480, 45, 80, 40))
        font = QtGui.QFont()
        font.setFamily("Unispace")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("QPushButton {    \n"
"    border: 3px solid #a81111;\n"
"    background-color: #700404;\n"
"    border-radius: 20;\n"
"    color: white;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #a81111\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #610202;\n"
"    border: 3px solid #610202;\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.label_3 = QtWidgets.QLabel(self.frame_2)
        self.label_3.setGeometry(QtCore.QRect(260, 10, 151, 41))
        font = QtGui.QFont()
        font.setFamily("Unispace")
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: white")
        self.label_3.setObjectName("label_3")
        self.lcdNumber = QtWidgets.QLCDNumber(self.frame_2)
        self.lcdNumber.setGeometry(QtCore.QRect(300, 60, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Unispace")
        font.setBold(True)
        font.setWeight(75)
        self.lcdNumber.setFont(font)
        self.lcdNumber.setObjectName("lcdNumber")
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setGeometry(QtCore.QRect(10, 140, 560, 331))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.frame_3.setFont(font)
        self.frame_3.setStyleSheet("background-color: #282e5c;\n"
"border-radius: 20")
        self.frame_3.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_3.setObjectName("frame_3")
        self.label_4 = QtWidgets.QLabel(self.frame_3)
        self.label_4.setGeometry(QtCore.QRect(30, 10, 401, 51))
        font = QtGui.QFont()
        font.setFamily("Unispace")
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: white")
        self.label_4.setObjectName("label_4")
        self.spinBox_3 = QtWidgets.QSpinBox(self.frame_3)
        self.spinBox_3.setGeometry(QtCore.QRect(465, 70, 50, 110))
        font = QtGui.QFont()
        font.setFamily("Unispace")
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.spinBox_3.setFont(font)
        self.spinBox_3.setStatusTip("")
        self.spinBox_3.setWhatsThis("")
        self.spinBox_3.setAccessibleName("")
        self.spinBox_3.setAccessibleDescription("")
        self.spinBox_3.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.spinBox_3.setStyleSheet("QSpinBox\n"
"{\n"
"    selection-background-color: #282e5c;\n"
"    color: white;\n"
"    padding-right: 5px;\n"
"    padding-left: 5px;\n"
"    padding-top: 25px;\n"
"    padding-bottom: 25px;\n"
"}\n"
"\n"
"QSpinBox::up-button\n"
"{\n"
"    width:45px;\n"
"    height: 30px;\n"
"    right: 3px;\n"
"    top: 2px;\n"
"}\n"
"\n"
"QSpinBox::down-button\n"
"{\n"
"    width:45px;\n"
"    height: 30px;\n"
"    right: 3px;\n"
"    bottom: 2 px;\n"
"}")
        self.spinBox_3.setInputMethodHints(QtCore.Qt.InputMethodHint.ImhDigitsOnly)
        self.spinBox_3.setWrapping(False)
        self.spinBox_3.setFrame(True)
        self.spinBox_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.spinBox_3.setReadOnly(False)
        self.spinBox_3.setButtonSymbols(QtWidgets.QAbstractSpinBox.ButtonSymbols.UpDownArrows)
        self.spinBox_3.setSpecialValueText("")
        self.spinBox_3.setKeyboardTracking(True)
        self.spinBox_3.setMaximum(59)
        self.spinBox_3.setObjectName("spinBox_3")
        self.pushButton_2 = QtWidgets.QPushButton(self.frame_3)
        self.pushButton_2.setGeometry(QtCore.QRect(180, 210, 190, 45))
        font = QtGui.QFont()
        font.setFamily("Unispace")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("QPushButton {    \n"
"    border: 3px solid #3051a8;\n"
"    border-radius: 20;\n"
"    color: white;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #3051a8\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #3bf3d4\n"
"}")
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_5 = QtWidgets.QLabel(self.frame_3)
        self.label_5.setGeometry(QtCore.QRect(45, 110, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Unispace")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color: white\n"
"")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.frame_3)
        self.label_6.setGeometry(QtCore.QRect(215, 110, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Unispace")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color: white\n"
"")
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.frame_3)
        self.label_7.setGeometry(QtCore.QRect(385, 110, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Unispace")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("color: white\n"
"")
        self.label_7.setObjectName("label_7")
        self.spinBox_4 = QtWidgets.QSpinBox(self.frame_3)
        self.spinBox_4.setGeometry(QtCore.QRect(125, 70, 50, 110))
        font = QtGui.QFont()
        font.setFamily("Unispace")
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.spinBox_4.setFont(font)
        self.spinBox_4.setToolTip("")
        self.spinBox_4.setStatusTip("")
        self.spinBox_4.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.spinBox_4.setAutoFillBackground(False)
        self.spinBox_4.setStyleSheet("QSpinBox\n"
"{\n"
"    selection-background-color: #282e5c;\n"
"    color: white;\n"
"    padding-right: 5px;\n"
"    padding-left: 5px;\n"
"    padding-top: 25px;\n"
"    padding-bottom: 25px;\n"
"}\n"
"\n"
"QSpinBox::up-button\n"
"{\n"
"    width:45px;\n"
"    height: 30px;\n"
"    right: 3px;\n"
"    top: 2px;\n"
"}\n"
"\n"
"QSpinBox::up-arrow \n"
"{\n"
"    \n"
"}\n"
"\n"
"QSpinBox::down-button\n"
"{\n"
"    width:45px;\n"
"    height: 30px;\n"
"    right: 3px;\n"
"    bottom: 2 px;\n"
"}")
        self.spinBox_4.setWrapping(False)
        self.spinBox_4.setFrame(True)
        self.spinBox_4.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.spinBox_4.setButtonSymbols(QtWidgets.QAbstractSpinBox.ButtonSymbols.UpDownArrows)
        self.spinBox_4.setSpecialValueText("")
        self.spinBox_4.setKeyboardTracking(True)
        self.spinBox_4.setMaximum(24)
        self.spinBox_4.setObjectName("spinBox_4")
        self.spinBox_5 = QtWidgets.QSpinBox(self.frame_3)
        self.spinBox_5.setGeometry(QtCore.QRect(295, 70, 50, 110))
        font = QtGui.QFont()
        font.setFamily("Unispace")
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.spinBox_5.setFont(font)
        self.spinBox_5.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.spinBox_5.setStyleSheet("QSpinBox\n"
"{\n"
"    selection-background-color: #282e5c;\n"
"    color: white;\n"
"    padding-right: 5px;\n"
"    padding-left: 5px;\n"
"    padding-top: 25px;\n"
"    padding-bottom: 25px;\n"
"}\n"
"\n"
"QSpinBox::up-button\n"
"{\n"
"    width:45px;\n"
"    height: 30px;\n"
"    right: 3px;\n"
"    top: 2px;\n"
"}\n"
"\n"
"QSpinBox::down-button\n"
"{\n"
"    width:45px;\n"
"    height: 30px;\n"
"    right: 3px;\n"
"    bottom: 2 px;\n"
"}")
        self.spinBox_5.setWrapping(False)
        self.spinBox_5.setFrame(True)
        self.spinBox_5.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.spinBox_5.setButtonSymbols(QtWidgets.QAbstractSpinBox.ButtonSymbols.UpDownArrows)
        self.spinBox_5.setSpecialValueText("")
        self.spinBox_5.setKeyboardTracking(True)
        self.spinBox_5.setMaximum(59)
        self.spinBox_5.setObjectName("spinBox_5")
        AlarmClock.setCentralWidget(self.centralwidget)

        self.retranslateUi(AlarmClock)
        QtCore.QMetaObject.connectSlotsByName(AlarmClock)

    def retranslateUi(self, AlarmClock):
        _translate = QtCore.QCoreApplication.translate
        AlarmClock.setWindowTitle(_translate("AlarmClock", "MainWindow"))
        self.label.setText(_translate("AlarmClock", "Timer"))
        self.pushButton.setText(_translate("AlarmClock", "Back"))
        self.label_3.setText(_translate("AlarmClock", "Time now"))
        self.label_4.setText(_translate("AlarmClock", "Set the time for timer"))
        self.pushButton_2.setText(_translate("AlarmClock", "Run Timer"))
        self.label_5.setText(_translate("AlarmClock", "Hours"))
        self.label_6.setText(_translate("AlarmClock", "Min-s"))
        self.label_7.setText(_translate("AlarmClock", "Sec-s"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    AlarmClock = QtWidgets.QMainWindow()
    ui = Ui_AlarmClock()
    ui.setupUi(AlarmClock)
    AlarmClock.show()
    sys.exit(app.exec())