# Form implementation generated from reading ui file 'Timer_3win.ui'
#
# Created by: PyQt6 UI code generator 6.3.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class UiTimerEnd(object):
    def setup_ui(self, timer_end):
        timer_end.setObjectName("timer_end")
        timer_end.resize(600, 500)
        timer_end.setMinimumSize(QtCore.QSize(600, 500))
        timer_end.setMaximumSize(QtCore.QSize(600, 500))
        timer_end.setAutoFillBackground(False)
        timer_end.setStyleSheet("background-color: #0d1131;")
        self.centralwidget = QtWidgets.QWidget(timer_end)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(10, 10, 580, 480))
        self.frame.setStyleSheet("background-color: #181b3f;\n"
                                 "border-radius: 20")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setGeometry(QtCore.QRect(10, 10, 560, 460))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.frame_3.setFont(font)
        self.frame_3.setStyleSheet("background-color: #282e5c;\n"
                                   "border-radius: 20")
        self.frame_3.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_3.setObjectName("frame_3")
        self.label_4 = QtWidgets.QLabel(self.frame_3)
        self.label_4.setGeometry(QtCore.QRect(90, 20, 380, 80))
        font = QtGui.QFont()
        font.setFamily("Unispace")
        font.setPointSize(48)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: white")
        self.label_4.setObjectName("label_4")
        self.res_btn = QtWidgets.QPushButton(self.frame_3)
        self.res_btn.setEnabled(True)
        self.res_btn.setGeometry(QtCore.QRect(40, 370, 200, 45))
        font = QtGui.QFont()
        font.setFamily("Unispace")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.res_btn.setFont(font)
        self.res_btn.setStyleSheet("QPushButton {    \n"
                                   "    border: 3px solid #3051a8;\n"
                                   "    border-radius: 20;\n"
                                   "    color: white;\n"
                                   "}\n"
                                   "\n"
                                   "QPushButton:hover {\n"
                                   "    background-color: #3051a8\n"
                                   "}\n"
                                   "\n"
                                   "QPushButton:pressed {\n"
                                   "    background-color: #3bf3d4\n"
                                   "}")
        self.res_btn.setObjectName("res_btn")
        self.label = QtWidgets.QLabel(self.frame_3)
        self.label.setGeometry(QtCore.QRect(170, 120, 210, 210))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("../../Desktop/Python/timer/timer_icon2_1_3.png"))
        self.label.setObjectName("label")
        self.menu_btn = QtWidgets.QPushButton(self.frame_3)
        self.menu_btn.setEnabled(True)
        self.menu_btn.setGeometry(QtCore.QRect(320, 370, 200, 45))
        font = QtGui.QFont()
        font.setFamily("Unispace")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.menu_btn.setFont(font)
        self.menu_btn.setStyleSheet("QPushButton {    \n"
                                    "    border: 3px solid #3051a8;\n"
                                    "    border-radius: 20;\n"
                                    "    color: white;\n"
                                    "}\n"
                                    "\n"
                                    "QPushButton:hover {\n"
                                    "    background-color: #3051a8\n"
                                    "}\n"
                                    "\n"
                                    "QPushButton:pressed {\n"
                                    "    background-color: #3bf3d4\n"
                                    "}")
        self.menu_btn.setObjectName("menu_btn")
        timer_end.setCentralWidget(self.centralwidget)

        self.retranslate_ui(timer_end)
        QtCore.QMetaObject.connectSlotsByName(timer_end)

    def retranslate_ui(self, timer_end):
        _translate = QtCore.QCoreApplication.translate
        timer_end.setWindowTitle(_translate("timer_end", "MainWindow"))
        self.label_4.setText(_translate("timer_end", "TIME\'S UP!"))
        self.res_btn.setText(_translate("timer_end", "Restart Timer"))
        self.menu_btn.setText(_translate("timer_end", "Main Menu"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    timer_end = QtWidgets.QMainWindow()
    ui = UiTimerEnd()
    ui.setup_ui(timer_end)
    timer_end.show()
    sys.exit(app.exec())
